name: CI/CD Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 4️⃣ Build the Next.js app
      - name: Build Next.js
        run: npm run build

      # 5️⃣ Compress build output before sending (recommended)
      - name: Create deployment archive
        run: tar -czf deploy.tar.gz .next package.json package-lock.json public next.config.js

      # 6️⃣ Copy files to EC2 (securely)
      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "deploy.tar.gz"
          target: "/var/www/baby_bliss"
          strip_components: 0
          overwrite: true
          debug: true
          timeout: 120
          command_timeout: 120

      # 7️⃣ SSH into EC2 and deploy app
      - name: SSH and restart app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/baby_bliss

            # Extract new build
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz

            # Install only production dependencies
            npm ci --omit=dev

            # Restart app with PM2
            pm2 delete baby_bliss || true
            pm2 start npm --name "baby_bliss" -- start
            pm2 save
