name: CI/CD Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - master  # Run only when master is updated

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build Next.js app
      run: npm run build

    - name: Upload build to EC2
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        # Copy only necessary files to reduce upload size
        source: |
          .next
          public
          package.json
          package-lock.json
          next.config.js
        target: /var/www/baby_bliss/baby_bliss

    - name: SSH into EC2 and restart app
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /var/www/baby_bliss/baby_bliss
          echo "Installing production dependencies..."
          npm install --production
          echo "Restarting PM2 app..."
          pm2 delete baby_bliss || true
          pm2 start npm --name "baby_bliss" -- start
          pm2 save
          pm2 list
